## postgres image repository
image: "postgres"
## postgres image version
## ref: https://hub.docker.com/r/library/postgres/tags/
##
imageTag: "9.6.2"

## Create a database user
## Default: postgres
postgresUser: "admin"
## Default: random 10 character string
postgresPassword: "123456"

## Create a database
## Default: the postgres user
postgresDatabase: "foo"

## Persist data to a persitent volume
persistence:
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  storageClass: default
  accessMode: ReadWriteOnce
  size: 8Gi
