---
apiVersion: v1
kind: Service
metadata:
  name: es-client
  labels:
    product: elk
    component: elasticsearch
    role: client
spec:
  type: LoadBalancer
  selector:
    product: elk
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    targetPort: 9200
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  labels:
    product: elk
    component: elasticsearch
    role: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        product: elk
        component: elasticsearch
        role: client
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      - name: es-client
        image: elasticsearch:5.2.0
        env:
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - -Ecluster.name=escluster
        - -Enode.name=${HOSTNAME}
        - -Ediscovery.zen.ping.unicast.hosts=es-master.${NAMESPACE}.svc.cluster.local
        - -Etransport.host=0.0.0.0
        - -Enode.master=false
        - -Enode.data=false
        - -Enode.ingest=false
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - name: data-volume
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: data-volume
        emptyDir: {}
