---
apiVersion: v1
kind: Service
metadata:
  name: es-master
  labels:
    product: elk
    component: elasticsearch
    role: master
spec:
  clusterIP: None
  selector:
    product: elk
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-master
  labels:
    product: elk
    component: elasticsearch
    role: master
spec:
  serviceName: "es-master"
  replicas: 1
  template:
    metadata:
      labels:
        product: elk
        component: elasticsearch
        role: master
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: es-master
        image: elasticsearch:5.2.0
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        args:
        - -Ecluster.name=escluster
        - -Enode.name=${HOSTNAME}
        - -Ediscovery.zen.ping.unicast.hosts=es-master.${NAMESPACE}.svc.cluster.local
        - -Ediscovery.zen.minimum_master_nodes=1
        - -Etransport.host=0.0.0.0
        - -Enode.master=true
        - -Enode.data=false
        - -Enode.ingest=false
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: data-volume
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
      annotations:
        volume.beta.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
